### ISSUE TITLE
Couldn't restore state

### ISSUE THREAD

**Issue by nik31096** [SvenGronauer/Bullet-Safety-Gym#3]
Hello! 
I got the following error trying to run minimal example from the repo main page:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/33044722/170881221-f7d63b6a-eb68-47ed-9682-acd4ff2a76b6.png">
My system is macOS Monterey 12.2.1 (MacBook Pro).
Library versions: 
- gym: 0.24.0
- bullet-safety-gym: 0.1
- pybullet: 3.2.5
- numpy: 1.21.2

Can you please comment on this issue and point out what I'm doing wrong? 😑

**Comment by SvenGronauer** [comment]
Hi!

I am running the attached Python code on macOS Monterey 12.4 (MacBook Pro Version 2019) with the library versions and it works for me:

gym: 0.20.0
bullet-safety-gym: 0.1
pybullet: 3.2.5
numpy: 1.21.2

Please try to downgrade the gym package to an older version.


```
import gym
import bullet_safety_gym

env = gym.make('SafetyAntCircle-v0')

while True:
    done = False
    env.render()  # make GUI of PyBullet appear
    x = env.reset()
    while not done:
        random_action = env.action_space.sample()
        x, reward, done, info = env.step(random_action)
```

**Comment by nikkostin** [comment]
Sorry for a long silence! Downgrade indeed helped, thanks a lot!!
